### ISSUE TITLE
Feature request for iter\concat

### ISSUE THREAD

**Issue by CMCDragonkai** [nikic/iter#37]
Similar to the `iter\flatten`, except it flattens by 1 step. This is very useful in many areas where your generators are yielding arrays and you want that to be unit of data to work with.

Here's an implementation:

```
function concat ($iterable) {
    return iter\reduce(
        function ($chainedIterables, $nextIterable) {
            return iter\chain($chainedIterables, $nextIterable);
        },
        $iterable,
        []
    );
}
```

This should be equivalent to a foldl concat implementation in Haskell.

**Comment by nikic** [comment]
Sounds reasonable, but I would like to have a better name than `concat`. It's hard to keep `chain` and `concat` apart. But not sure what a good name would be.

An alternative would be to add a `$level` argument to `flatten`, which limits how deep the flattening is performed.

**Comment by CMCDragonkai** [comment]
Flatten could default to 1 level with 0 meaning all levels.

**Comment by CMCDragonkai** [comment]
It's also something that is required for `flatMap` function. Similar to haskell's `>>=` "bind" combinator. The Functional library has this: https://github.com/lstrojny/functional-php/blob/master/docs/functional-php.md#other-2

**Comment by CMCDragonkai** [comment]
Here is an implementation for flatMap:

```php
        $flatMap = function ($iterable, $action) use ($concat) {
            return $concat(iter\map($action, $iterable));
        };
```

**Comment by nikic** [comment]
I've just added the `$levels` argument to flatten() in https://github.com/nikic/iter/commit/b977e870a46395564a6b110b7b39943025400f46 and a flatMap() function in https://github.com/nikic/iter/commit/e3ff3052ecd3bb9d5b3c46fc5391f696527f72b4 :)
