### ISSUE TITLE
Use iterator_to_array

### ISSUE THREAD

**Issue by SamMousa** [nikic/iter#44]
Is there any reason not to use `iterator_to_array` instead of "manually" interating in the `toArray` and `toArrayWithKeys` implementations?

**Comment by SamMousa** [comment]
Oh, never mind; obviously the built-in function doesn't accept normal arrays

**Comment by nikic** [comment]
Additionally the built-in functions have a bad default of preserving keys, which regularly bites people trying to use it together with generators.

**Comment by SamMousa** [comment]
Can you explain why preserving keys is bad?

**Comment by nikic** [comment]
Take something like `iterator_to_array(concat(range(1,9), range(10,19))`. What you will get as a result is just the second range, because the keys will be overwritten. This happens quite often when using iterators.
