### ISSUE TITLE
1.6 Release

### ISSUE THREAD

**Issue by ragboyjr** [nikic/iter#48]
@nikic Is there anything you need help with to get a 1.6 release? Just wondering when we see a 1.6 release with the latest code that was merged in.

Thanks for the awesome library btw

**Comment by nikic** [comment]
New version released (https://github.com/nikic/iter/releases/tag/v1.6.0), sorry for not doing it earlier!

**Comment by ragboyjr** [comment]
Thank you so much! @nikic
