### ISSUE TITLE
Pass key to map function

### ISSUE THREAD

**Issue by SamMousa** [nikic/iter#64]
Is there any reason for not passing both key and value to the `mapKeys` and `map` functions?

I find myself often wanting to use both even when just changing one.

Currently one option is to use `enumerate`, but it makes the code a lot longer than it needs to be.

**Comment by jvasseur** [comment]
On reason (and the reason why it would be a BC break to change it) is if you use a function that has a second optional argument, by only passing the value you can use the default value of this argument. On example I have in mind would be `map('intval', $iterable);`.

**Comment by SamMousa** [comment]
Hmm that's a good point, so we can't change the `map` and `mapKeys` functions themselves.
Is there any reason not to have `mapWithKeys` and `mapKeysWithKeys`?

**Comment by Bilge** [comment]
This is a major oversight.

**Comment by dakujem** [comment]
It's not as simple as `$result = array_map($mapper, $array, array_keys($array))` though.\
`array_map` will **discard keys** from the original `$array` in the `$result` if more than one argument is passed to it ([PHP manual](https://www.php.net/manual/en/function.array-map.php#refsect1-function.array-map-returnvalues)).

If someone wants **to retain the keys** for a reason and still use both the key and the value in the mapper function, something like the following needs to be used:
```php
$keys = array_keys($array);
$result = array_combine($keys, array_map($mapper, $array, $keys));
```

I recently released a function [`array_map_keys`](https://github.com/dakujem/remapkeys/blob/master/src/map.php) that fills this hole in the PHP core. The function allows to use the keys (or other additional arguments to `array_map`) without sacrificing the keys in the resulting array.

**Comment by drupol** [comment]
I guess this can be closed now, `mapWithKeys()` has been committed. See https://github.com/nikic/iter/commit/170f93c2c64ee9c18d8f6f7bed189b0288cc8069

**Comment by Bilge** [comment]
How did you get so good at guessing?

**Comment by drupol** [comment]
> How did you get so good at guessing?

?
