### ISSUE TITLE
Feature: Add generators support

### ISSUE THREAD

**Issue by SerafimArts** [nikic/iter#74]
The current implementation works with generalized iterators, which interferes with working with generators. Thus, a simple function does not "throw" out the interaction functional with the second part of the coroutine.

**Current Implementation**

```php
function map(callable $function, iterable $iterable): \Iterator {
    foreach ($iterable as $key => $value) {
        yield $key => $function($value);
    }
}
```

**Usage Example**

```php
function source() {
    echo yield 1;
}

$iterator = map(operator('*', 2), source());

while ($iterator->valid()) {
  $iterator->send($iterator->current());
}
```

**Actual**

Displays the number 1

**Expected**

Displays the number 2

**Offered**

This problem affects almost the entire functionality, not only the map method.
No support for the `->send` coroutine method and `return` operator.

It would be desirable to change behavior, having resulted it approximately to the following:

```php
function toGenerator(iterable $iterable): \Generator {
    yield from $iterable;

    if ($iterable instanceof \Generator) {
        return $iterable->getReturn();
    }
}


function map(callable $function, iterable $iterable): \Iterator {
    $generator = toGenerator($iterable);

    while ($generator->valid()) {
        [$key, $value] = [$generator->key(), $generator->current()];

        $generator->send(yield $key => $function($value));
    }

    return $generator->getReturn();
}


function reverseMap(callable $function, iterable $iterable): \Iterator {
    $generator = toGenerator($iterable);

    while ($generator->valid()) {
        [$key, $value] = [$generator->key(), $generator->current()];

        $generator->send($function(yield $key => $value));
    }

    return $generator->getReturn();
}
```

**Comment by nikic** [comment]
I kind of see what you're trying to do here, but I don't really understand what the use-case for something like this would be. In my experience, generators are used as either pure producers (i.e. Iterators, what this library deals with), pure consumers (much more rare, for some push-based data processing) or specifically as coroutines (where yielded values are promises or similar). Your map() implementation seems to aim at some kind of mixed producer-consumer case. Did you have anything specific in mind there?

**Comment by SerafimArts** [comment]
Frankly, I can not remember those cases when it took a year ago and now I cannot even invent a common task for this example. 

So I propose to just close this issue
