### ISSUE TITLE
\iter\map does not accept all kinds of callable?

### ISSUE THREAD

**Issue by vfsoraki** [nikic/iter#84]
I was trying to use `\iter\map` like this:

```
\iter\map([$this, 'aFunction'], $iterable)
```

But `map` does not accept this kind of callable. Reading source shows this:

```
function map(callable $function, iterable $iterable): \Iterator {
    foreach ($iterable as $key => $value) {
        yield $key => $function($value);
    }
}
```

Why `$function(value)` and not `call_user_func($function, $value)`? I don't see why, shed some light here please.

**Comment by nikic** [comment]
All callbacks are supported. Most likely the issue is that `[$this, 'aFunction']` is a private function. You need to use `Closure::fromCallable([$this, 'aFunction'])` in that case.

PS: Please, absolutely never use `call_user_func()`.

**Comment by vfsoraki** [comment]
> All callbacks are supported. Most likely the issue is that `[$this, 'aFunction']` is a private function. You need to use `Closure::fromCallable([$this, 'aFunction'])` in that case.
> 
> PS: Please, absolutely never use `call_user_func()`.

Oh yes, `protected` was it. Thanks!

BTW, why not use `call_user_func`?
